# Generated by Django 4.2.2 on 2024-10-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailmanager', '0006_alter_sendattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendattempt',
            name='attempts_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество попыток'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailmanager.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='last_attempt_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='last_attempt_status',
            field=models.CharField(blank=True, choices=[('success', 'успешно'), ('failed', 'не успешно')], max_length=255, null=True, verbose_name='Статус последней попытки'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailmanager.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
